/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "MapProxy im Praxiseinsatz",
  "tagline": "FOSSGIS Workshop",
  "favicon": "img/favicon.ico",
  "url": "https://your-docusaurus-test-site.com",
  "baseUrl": "/MapProxy_Workshop_Praxiseinsatz/",
  "organizationName": "terrestris",
  "projectName": "MapProxy_Workshop_Praxiseinsatz",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "de",
    "locales": [
      "de"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/home/hblitza/workspace/MapProxy_Workshop_Praxiseinsatz/sidebars.js"
        },
        "theme": {
          "customCss": "/home/hblitza/workspace/MapProxy_Workshop_Praxiseinsatz/src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/mapproxy.png",
    "navbar": {
      "title": "MapProxy im Praxiseinsatz",
      "logo": {
        "alt": "MapProxy logo",
        "src": "img/mapproxy.png"
      },
      "items": [
        {
          "type": "doc",
          "docId": "introduction/intro",
          "position": "left",
          "label": "Workshop"
        },
        {
          "type": "html",
          "position": "right",
          "value": "<div class=\"header-logo-right\"><img height=\"32px\" src=\"/MapProxy_Workshop_Praxiseinsatz/img/fossgis_logo.png\" /><img height=\"32px\" src=\"/MapProxy_Workshop_Praxiseinsatz/img/logo_terrestris_small3.png\" /></div>"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "More",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/terrestris/MapProxy_Workshop_Praxiseinsatz"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2023 @terrestris. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
